#!/bin/bash

# ===========================================================================
# GLOBAL VARIABLES
# ===========================================================================
SESSION=$2
GROUP=$2

# tmuxinator config files path
TM_PATH="/Users/jose8a/.tmuxinator"

# TODO: remove this hard-coded $PO_GROUPS path and set it via the `install.sh` script
PO_GROUPS="/Users/jose8a/jdev/po-projects"
RESTART_FILE="$PO_GROUPS/RESTART.list"

# TODO: remove this hard-coded path and set it via the `install.sh` script
SCRIPT_PATH="$HOME/jdev/l0/po"

HELP="$SCRIPT_PATH/HELP"

# ===========================================================================
# FUNCTIONS
# ===========================================================================
source "$SCRIPT_PATH/po-functions.sh"



# ===========================================================================
# USER-INPUT ROUTER
# ===========================================================================
case $1 in
  -h)
      po_show_help
      ;;
  -a)
      po_attach_session
      ;;
  -c)
      po_display_configuration
      ;;
  -d)
      po_detach_session
      ;;
  -e)
      po_edit_configuration
      ;;
  -l)
      po_display_launchers
      ;;
  -L)   # TODO
      echo "TODO: this option not yet implemented. Check back later!"
      ;;
  -n)
      po_create_session
      ;;
  -o)
      po_open_one
      ;;
  -O)
      po_open_group
      ;;
  -r)
      po_show_running
      ;;
  -s)
      po_save_running_sessions
      ;;
  -x)
      po_stop_one
      ;;
  -X)
      echo "TODO: this option not yet implemented. Check back later!"
       po_stop_all
      ;;
  -z)
      po_create_scratch
      ;;
  *)
      po_option_error_banner
      po_show_help
      ;;
esac
