#!/usr/bin/env node

/**
 * Module dependencies.
 */
const po = require('commander');
const sh = require('shelljs');
const chalk = require('chalk');
require('paint-console');

// TODO: remove these from the project.  Only paint-console needed
// for color output on errors.
// --- const signale = require('signale');

/*
 * TODO: Quit if the project folders have NOT been set up
 */


/*
 * Command handlers
 *  - using Commander.js 'git-style sub-commands' pattern
 *    for each of the below handlers
 */
const handleAttach = require('./attachHandler');
const handleDetach = require('./detachHandler');
const handleEdit = require('./editHandler');
const handleContent = require('./contentHandler');
const handleListing = require('./listHandler');
const handleCreate = require('./createHandler');
const handleOpen = require('./openHandler');
const handleSnapshot = require('./snapshotHandler');
const handleStop = require('./stopHandler');
const handleHistory = require('./historyHandler');
const handleScratch = require('./scratchHandler');

po.version('0.1.0')


/*
 * Instantiate the command handlers
 */
handleAttach(po);
handleContent(po);
handleDetach(po);
handleEdit(po);
handleListing(po);
handleCreate(po);
handleOpen(po);
handleSnapshot(po);
handleStop(po);
handleHistory(po);
handleScratch(po);

po.parse(process.argv);

